INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('Frnech');
INSERT INTO category (description) VALUES ('Korean');
INSERT INTO category (description) VALUES ('Mexican');
INSERT INTO unit_of_measure (uom) VALUES ('Teaspoon');
//INSERT INTO unit_of_measure (uom) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (uom) VALUES ('Cup');
INSERT INTO unit_of_measure (uom) VALUES ('Pinch');
INSERT INTO unit_of_measure (uom) VALUES ('Ounce');
INSERT INTO unit_of_measure (uom) VALUES ('2 ripe avocados');
INSERT INTO unit_of_measure (uom) VALUES ('1/4 teaspoon kosher salt, plus more to taste');
INSERT INTO unit_of_measure (uom) VALUES ('1 tablespoon fresh lime or lemon juice');
INSERT INTO unit_of_measure (uom) VALUES ('2 to 4 tablespoons minced red onion or thinly sliced green onion');
INSERT INTO unit_of_measure (uom) VALUES ('1 to 2 serrano (or jalapeño) chilis, stems and seeds removed, minced');
INSERT INTO unit_of_measure (uom) VALUES ('2 tablespoons cilantro (leaves and tender stems), finely chopped');
INSERT INTO unit_of_measure (uom) VALUES ('Pinch freshly ground black pepper');
INSERT INTO unit_of_measure (uom) VALUES ('1/2 ripe tomato, chopped (optional)');
INSERT INTO unit_of_measure (uom) VALUES ('Red radish or jicama slices for garnish (optional)');

